export const FETCH_CART_CREATE_REQUEST = 'FETCH_PRODUCT_CREATE_REQUEST';
export const FETCH_CART_CREATE_SUCCESS = 'FETCH_PRODUCT_CREATE_SUCCESS';
export const FETCH_CART_CREATE_FAIL = 'FETCH_PRODUCT_CREATE_FAIL';
