export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL';

export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAIL = 'FETCH_PRODUCT_DETAILS_FAIL';

export const FETCH_PRODUCT_CREATE_REQUEST = 'FETCH_PRODUCT_CREATE_REQUEST';
export const FETCH_PRODUCT_CREATE_SUCCESS = 'FETCH_PRODUCT_CREATE_SUCCESS';
export const FETCH_PRODUCT_CREATE_FAIL = 'FETCH_PRODUCT_CREATE_FAIL';

export const FETCH_PRODUCT_DELETE_REQUEST = 'FETCH_PRODUCT_DELETE_REQUEST';
export const FETCH_PRODUCT_DELETE_SUCCESS = 'FETCH_PRODUCT_CREATE_SUCCESS';
export const FETCH_PRODUCT_DELETE_FAIL = 'FETCH_PRODUCT_CREATE_FAIL';
